# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'YouTube' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouTube
  pod 'IQKeyboardManager', '~> 6.2.0'
  pod 'SnapKit', '~> 4.2.0'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'HandyJSON', '~> 4.2.1'
  pod 'NicooPlayer'
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'AudioPlayerSwift'
  
  
end
